#include <stdio.h> /* printf, scanf, NULL */
#include <stdlib.h> /* malloc, free, rand */
#include <assert.h>
#include <stdarg.h>
#include <time.h>

int dyn_println(FILE* out, const char* format, ...)
{
    va_list args;

    va_start(args, format);
    int len = vsnprintf(NULL, 0, format, args) + 1;
    va_end(args);

    char* msg = (char*)malloc(len * sizeof(char));
    assert(msg && "out of mem ... buy more ram?");

    va_start(args, format);
    vsnprintf(msg, len, format, args);
    va_end(args);

    if (out)
        fprintf(out, "%s\n", msg);

    free(msg);

    return len;
}

int sta_println(FILE* out, const char* format, ...)
{
    va_list args;
    char msg[1024] = {};

    va_start(args, format);
    int len = vsnprintf(msg, sizeof(msg), format, args);
    va_end(args);

    if (out)
        printf("%s\n", msg);

    return len;
}

void start(clock_t* cl)
{
    *cl = clock();
}

void report(clock_t* cl)
{
    clock_t difference = clock() - *cl;
    int sec = difference / CLOCKS_PER_SEC;

    printf("\nTime: %d sec (%ld ms)", sec, difference);
    fflush(stdout);
}

const char* rand_text[] = {
    "In 1854, he began to attend Domgymnasium in Naumburg. Because his father had worked for the state (as a pastor) the now-fatherless Nietzsche was offered a scholarship to study at the internationally recognized Schulpforta (the claim that Nietzsche was admitted on the strength of his academic competence has been debunked: his grades were nowhere near the top of the class)",
    "Nietzsche subsequently concentrated on studying philology under Professor Friedrich Wilhelm Ritschl, whom he followed to the University of Leipzig in 1865.[18] There, he became close friends with his fellow student Erwin Rohde. Nietzsche's first philological publications appeared soon after.",
    "This number is generated by an algorithm that returns a sequence of apparently non-related numbers each time it is called. This algorithm uses a seed to generate the series, which should be initialized to some distinctive value using function srand.",
    "Just something small",
    "More small",
    "Super small!",
    "Sm!"
};

#define MAX_ITER 10000000

int main(int argc, const char* argv[])
{
    int msg_count = sizeof(rand_text) / sizeof(char*);
    int max_iter = MAX_ITER;

    if (argc == 2) {
        max_iter = atoi(argv[1]);
        max_iter = max_iter < 1 ? 1000 : max_iter;
    }

    dyn_println(stdout, "Testing %d times with %d rand masages", max_iter, msg_count);

    fflush(stdout);

    sta_println(stdout, ".");
    clock_t sw;
    start(&sw);

    for (int i = 0; i < max_iter; ++i) {
        sta_println(NULL, "%d %s", i, rand_text[rand() % msg_count]);
    }

    report(&sw);
    start(&sw);

    for (int i = 0; i < max_iter; ++i) {
        dyn_println(NULL, "%d %s", i, rand_text[rand() % msg_count]);
    }

    report(&sw);

    return 0;
}
